#fos_user_override:
#    resource: "@FosUserOverrideBundle/Resources/config/routing.yml"
#    prefix:   /

#user_override:
#    resource: "@UserOverrideBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
